
<?php 
require_once 'app/templates/header.phtml';

$isEdit = isset($client);  
?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Clientes</title>
    <link rel="stylesheet" href="/primeraChamba/estilos/cliente.css">
</head>
<div class="container">
<div class="form-section">
    <h2><?= $isEdit ? "Editar cliente" : "Agregar nuevo cliente" ?></h2>

    <form action="<?= $isEdit ? BASE_URL . 'modificarCliente/' . $client->id : BASE_URL . 'agregarCliente' ?>" method="POST" enctype="multipart/form-data">
        <div class="form-group">
                    <label for="nameInput">Nombre del cliente</label>
                    <input name="name" type="text" class="form-control" id="nameInput" placeholder="Nombre del cliente" 
                        value="<?= $isEdit ? $client->nombre : '' ?>">
                
            </div>
            <div class="form-group">
                    <label for="nameInput">DNI</label>
                    <input name="dni" type="number" class="form-control" id="dniInput" placeholder="DNI" 
                        value="<?= $isEdit ? $client->dni : '' ?>">
                
            
            </div>

            <div class="form-group">
                <label for="cellphone">Telefono</label>
                    <input name="cellphone" type="number" class="form-control" id="cellInput" placeholder="Telefono del cliente" 
                        value="<?= $isEdit ? $client->telefono : '' ?>">
                   
                   
                
            </div>

            <div class="form-group">
            <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>

</div>
<a href="<?php echo BASE_URL; ?>clientes" class="btn btn-primary" id="volver" >VOLVER</a>
</div>


<?php 
require_once 'app/templates/footer.phtml';
?>




