<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="estilos/header.css">
    <title>Grutzky Pedersen Motos</title>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid d-flex justify-content-between">
            <a class="navbar-brand" href="">
                <img src="\primeraChamba\static\Logo2.png" alt="Logo" class="logonav">
            </a>
            <div class="navbar-nav">
                <ul class="navbar-nav ms-auto"> 
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?php echo BASE_URL ?>clientes">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?php echo BASE_URL ?>motos">Motos</a>
                    </li>
                    
                     <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?php echo BASE_URL ?>calendario">Calendario</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?php echo BASE_URL ?>historial">Turnos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
</body>
