<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Clientes</title>
    <link rel="stylesheet" href="/primeraChamba/estilos/turno.css">
</head>
<body>

<?php require './app/templates/header.phtml';
$isEdit = isset($turn);   
?>

<div class="container">
<div class="right-section">
<?php if (isset($_SESSION['error_message'])): ?>
    <div class="alert alert-danger">
        <?php 
            echo $_SESSION['error_message']; 
            unset($_SESSION['error_message']); // Eliminar después de mostrar
        ?>
    </div>
<?php endif; ?>
        <h2>Buscar Turno</h2>
        <form action="<?php echo BASE_URL . 'turnoPatente'; ?>" method="GET" class="d-flex">
        <input type="text" name="patente" class="form-control me-2" placeholder="Ingrese la patente del turno..." required>
        <button type="submit" class="btn btn-secondary">Buscar</button>
        </form>
        <h2>Listado de Turnos en el sistema</h2>
        <div class="table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Ingreso</th>
                        <th>Entrega</th>
                        <th>Patente</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($turns as $turn) :?>
                        <tr>
                            <td><?php echo $turn->entrega?></td>
                            <td><?php echo $turn->ingreso ?></td>
                            <td><?php echo $turn->patente ?></td>
                            <td>
                                <a href="<?php echo BASE_URL . "verTurno/" . $turn->id; ?>" class="icon-btn" title="Ver detalles">🔍</a>
                                <a href="<?php echo BASE_URL . "modificarTurno/" . $turn->id; ?>" class="icon-btn" title="Editar">✏️</a>
                                <a href="<?php echo BASE_URL . "eliminarTurno/" . $turn->id; ?>" class="icon-btn delete-btn" title="Borrar" onclick="return confirm('¿Seguro que quieres borrar este turno?');">🗑️</a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
    </div>

    

<?php require './app/templates/footer.phtml'; ?>

</body>
</html>