<?php require './app/templates/header.phtml';?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Motos</title>
    <link rel="stylesheet" href="/primeraChamba/estilos/estilosMoto.css">
</head>
<body>
<div>
<h2>Clientes</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">DNI</th>
        <th scope="col">Telefono</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($clients as $client) :?>
      <tr>
        <th scope="row"><?php echo$client->nombre?></th>
        <td><?php echo $client->nombre ?></td>
        <td><a  href="<?php echo BASE_URL . "verCliente/" . $client->id?>">Ver Completo</a></td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
</div>
</body>
<div>
<?php require './app/templates/footer.phtml' ?>