<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/primeraChamba/estilos/login.css">
    <title>Login</title>
</head>
<body>

    <div class="dark-gradient"></div>

    <div class="container my-5 p-4 shadow-sm bg-light rounded">
        <?php if ($error): ?>
            <div class='alert error-message' role='alert'>
               * <?= $error ?>
            </div>
        <?php endif ?>
        <form id="login-form" method='POST' action='verificarLogin'>
            <h2>Iniciar sesión como administrador</h2>
            <div class="form">
                <div class='form-group'>
                    <input type='text' class='form-control' name='usuario' placeholder="Usuario" required>
                </div>
                <div class='form-group'>
                    <input type='password' class='form-control' name='contraseña' placeholder="Contraseña" required>
                </div>
                <button type='submit' class='btn btn-primary mt-2'>Iniciar sesión</button>
            </div>
        </form>
    </div>

    <h1 class="welcome-text">¡Bienvenido al panel de control!</h1>
    <h4 class="subtitulo">Ingrese sus datos para acceder</h4>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    

</body>
</html>

