<?php require 'app/templates/header.phtml'; ?>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Clientes</title>
    <link rel="stylesheet" href="/primeraChamba/estilos/estilosMoto.css">
</head>

<div class="container mt-5">
    
<div class="alert alert-success  text-center" role="alert">
          La operacion se realizo con exito 
      </div>

    <div class="text-center mt-4">
        <a href="<?php echo BASE_URL . 'home'; ?>" class="btn btn-primary">VOLVER</a>
    </div>
</div>

<?php require 'app/templates/footer.phtml'; ?>