
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Clientes</title>
    <link rel="stylesheet" href="/primeraChamba/estilos/turno.css">
</head>
<body>
<?php require './app/templates/header.phtml';
 ?>  
<div class="container">
    <div class="form-section">
        <h2>Formulario Turnos</h2>
        <h2>Orden de reparacion: 00<?= $turno->id ?></h2>
        <form action=" " method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="ingreso">Ingreso</label>
                <input name="ingreso" type="date" class="form-control" id="ingreso" placeholder="Fecha ingreso" value="<?= $turno->ingreso ?>">
            </div>

            <div class="form-group">
                <label for="dniInput">Entrega</label>
                <input name="entrega" type="date" class="form-control" id="entrega" placeholder="Fecha entrega" value="<?= $turno->ingreso ?>">
            </div>

            <div class="form-group">
                <label for="color">color</label>
                <input name="color" type="text" class="form-control" id="color" placeholder="Color" value=" ">
            </div>
            <div class="form-group">
                <label for="kilometros">kilometros</label>
                <input name="kilometros" type="number" class="form-control" id="kilometros" placeholder="kms" value=" ">
            </div>
           
            <div class="form-group">
                <label for="motor">Motor</label>
                <input name="motor" type="text" class="form-control" id="motor" placeholder="Motor" value=" ">
            </div>

            <div class="form-group">
                <label for="chasis">Chasis</label>
                <input name="chasis" type="text" class="form-control" id="chasis" placeholder="Chasis" value=" ">
            </div>

            <div class="form-group">
                <label for="patente">Patente</label>
                <input name="patente" type="text" class="form-control" id="patente" placeholder="Patente" value="<?= $turno->patente ?>">
            </div>

            <div class="form-group">
                <label for="modelo">Modelo</label>
                <input name="modelo" type="text" class="form-control" id="modelo" placeholder="Modelo" value="<?= $moto->modelo ?>">
            </div>

            <div class="form-group">
                <label for="nombre">Apellido y nombre</label>
                <input name="nombre" type="text" class="form-control" id="nombre" placeholder="Nombre" value="<?= $cliente->nombre ?>">
            </div>

            <div class="form-group">
                <label for="documento">Documento</label>
                <input name="documento" type="number" class="form-control" id="documento" placeholder="Documento" value="<?= $cliente->dni ?>">
            </div>

            <div class="form-group">
                <label for="direccion">Direccion</label>
                <input name="direccion" type="text" class="form-control" id="direccion" placeholder="Direccion" value=" ">
            </div>

            <div class="form-group">
                <label for="telefono">Telefono</label>
                <input name="telefono" type="number" class="form-control" id="telefono" placeholder="Telefono" value="<?= $cliente->telefono ?>">
            </div>

            <div class="form-group">
                <label for="descripcion">Descripcion</label>
                <input name="descripcion" type="text" class="form-control" id="descripcion" placeholder="Descripcion" value="<?= $moto->descripcion ?>">
            </div>

            <h2>Resumen del acuerdo</h2>
            <div class="form-group">
                <label for="conceptos">Conceptos</label>
                <input name="conceptos" type="text" class="form-control" id="conceptos" placeholder="Conceptos" value=" ">
            </div>

            <div class="form-group">
                <label for="conceptos">Conceptos</label>
                <input name="conceptos" type="text" class="form-control" id="conceptos" placeholder="Conceptos" value=" ">
            </div>

            <div class="form-group">
                <label for="ManoDeObra">Mano de obra</label>
                <input name="ManoDeObra" type="text" class="form-control" id="ManoDeObra" placeholder="Mano de obra" value=" ">
            </div>

            <div class="form-group">
                <label for="repuestos">Repuestos</label>
                <input name="repuestos" type="text" class="form-control" id="repuestos" placeholder="Repuestos" value=" ">
            </div>

            <div class="form-group">
                <label for="terceros">Trabajo de terceros</label>
                <input name="terceros" type="text" class="form-control" id="terceros" placeholder="Terceros" value=" ">
            </div>
            <h2>Combustible y aceite</h2>
            <div class="form-group">
                <label for="combustible">Combustible</label>
                <select name="combustible" class="form-control" id="combustible">
                    <option value="1/4">1/4</option>
                    <option value="1/2">1/2</option>
                    <option value="3/4" >3/4</option>
                    <option value="4/4" >4/4</option>
                </select>
            </div>

            <div class="form-group">
                <label for="aceite">Aceite en motor</label>
                <select name="aceite" class="form-control" id="aceite">
                    <option value="si">si</option>
                    <option value="no">no</option>
                </select>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        </form>
    </div>

<?php require './app/templates/footer.phtml'; ?>