<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/primerachamba/estilos/estilos.css">
    <title>Home</title>
</head>
<body>
    <header>
        <img src="\primeraChamba\static\Logo2.png" alt="Logo" class="logo">
    </header>
    <main class="home-container">
        <a href="/primerachamba/clientes">
        <button class="home-button">Clientes</button>
        </a>
        <a href="/primerachamba/motos"> 
        <button class="home-button">Motos</button>
        </a>
        
        <button class="home-button">Historial de turnos</button>
    </main>
</body>
</html>